#!/bin/sh

LENGTH="$(cat input | head -n 1 | tr -d '\n' | wc -m)"
HEIGHT="$(cat input | wc -l)"

xmas_count_line() {
  local M="$1"
  local INPUT_LINE=input."$M"
  local XMAS_COUNT=0
  XMAS_COUNT="$(( $(cat input \
    | tail -n +"$((M + 1))" \
    | head -n 1 \
    | tr -d '\n' \
    | sed 's/XMAS/\n/g' \
    | wc -l) ))"
  XMAS_COUNT="$((XMAS_COUNT + $(cat input \
    | tail -n +"$((M + 1))" \
    | head -n 1 \
    | tr -d '\n' \
    | sed 's/SAMX/\n/g' \
    | wc -l) ))"
  for N in $(seq 0 "$((LENGTH - 1))")
  do
    INPUT_LINE_POSITION="$INPUT_LINE"."$N"
    cat input | tail -n +"$((M + 1))" | tail -c +"$((N + 1))" | tr -d '\n' > "$INPUT_LINE_POSITION"
    XMAS_COUNT="$((XMAS_COUNT + $(cat "$INPUT_LINE_POSITION" \
      | sed "s/^X.\{$((LENGTH - 1))\}M.\{$((LENGTH - 1))\}A.\{$((LENGTH - 1))\}S/\n/g" \
      | wc -l) ))"
    XMAS_COUNT="$((XMAS_COUNT + $(cat "$INPUT_LINE_POSITION" \
      | sed "s/^S.\{$((LENGTH - 1))\}A.\{$((LENGTH - 1))\}M.\{$((LENGTH - 1))\}X/\n/g" \
      | wc -l) ))"
    if [ "$N" -ge "$((LENGTH - 4))" ]
    then
      continue
    fi
    XMAS_COUNT="$((XMAS_COUNT + $(cat "$INPUT_LINE_POSITION" \
      | sed "s/^X.\{$((LENGTH + 0))\}M.\{$((LENGTH + 0))\}A.\{$((LENGTH + 0))\}S/\n/g" \
      | wc -l) ))"
    XMAS_COUNT="$((XMAS_COUNT + $(cat "$INPUT_LINE_POSITION" \
      | sed "s/^.\{$((LENGTH + 3))\}X.\{$((LENGTH - 2))\}M.\{$((LENGTH - 2))\}A.\{$((LENGTH - 2))\}S/\n/g" \
      | wc -l) ))"
    XMAS_COUNT="$((XMAS_COUNT + $(cat "$INPUT_LINE_POSITION" \
      | sed "s/^S.\{$((LENGTH + 0))\}A.\{$((LENGTH + 0))\}M.\{$((LENGTH + 0))\}X/\n/g" \
      | wc -l) ))"
    XMAS_COUNT="$((XMAS_COUNT + $(cat "$INPUT_LINE_POSITION" \
      | sed "s/^.\{$((LENGTH + 3))\}S.\{$((LENGTH - 2))\}A.\{$((LENGTH - 2))\}M.\{$((LENGTH - 2))\}X/\n/g" \
      | wc -l) ))"
  done
  if [ "$DEBUG" = true ]
  then
    echo "Line $((M + 1)) done" >&2
  fi
  echo "$XMAS_COUNT" > xmas_count."$M"
}

if [ "$#" -gt 0 ]
then
  "$@"
  exit "$?"
fi

seq 0 "$((HEIGHT - 1))" \
  | xargs -I @M -P "${PARALLELISM:-$(getconf _NPROCESSORS_ONLN)}" env DEBUG="$DEBUG" sh $(printf %s "$-" | grep -q x && printf %s -x) solve xmas_count_line @M
XMAS_COUNT="$((XMAS_COUNT + $(cat xmas_count.* \
  | {
    XMAS_COUNT=0
    while read XMAS_COUNT_LINE
    do
      XMAS_COUNT="$((XMAS_COUNT+ XMAS_COUNT_LINE))"
    done
    echo "$XMAS_COUNT"
    }) ))"
echo "$XMAS_COUNT"
