#!/bin/sh

tr -s ' ' < input > input.trimmed
TOTAL=0
while read P REPORT <&3
do
  GOOD=true
  DIR=0
  for N in $REPORT
  do
    if [ "$P" -eq "$N" ]
    then
      GOOD=false
      break
    fi
    if [ "$P" -gt "$N" ]
    then
      if [ "$DIR" -gt 0 ] || [ "$((P - N))" -ge 4 ]
      then
        GOOD=false
        break
      fi
      DIR=-1
    else
      if [ "$DIR" -lt 0 ] || [ "$((N - P))" -ge 4 ]
      then
        GOOD=false
        break
      fi
      DIR=1
    fi
    P="$N"
  done
  if "$GOOD"
  then
    TOTAL="$((TOTAL + 1))"
  fi
done 3<input.trimmed
echo "$TOTAL"
